### PR TITLE
Bundle refactoring + performance fix

### PR DESCRIPTION
**Pull request by enumag**
I'm still testing the changes but you can have a look if you want. The performance issue was not easy to fix so I had to refactor many things in the bundle to reach the point where I could fix it.

----

Changelog:

- Simplified .gitignore.
- Raised version constraints to Symfony >= 3.3 and PHP >= 5.5.9.
- Removed legacy code for compatibility with Symfony < 2.4.
- Switched from PSR-0 to PSR-4.
- Removed useless whitespace and class/method descriptions.
- CsrfRouter no longer extends Symfony Router.
- Removed CsrfTokenManager, the logic was moved to other classes.
- Fixed major performance issue caused by usage of `getRouteCollection` (https://github.com/fantoine/csrf-route-bundle/issues/2).

### CODE REVIEW

**Comment by enumag** [comment]
@fantoine What do you think?

**Comment by fantoine** [comment]
Thanks for this big update! 👍

**Comment by enumag** [comment]
Oh... I didn't expect you to merge it right away, I just wanted your opinion first.

Well whatever, just don't tag it yet, I want to finish the todos above first. Your opinion is still welcomed of course.

**Comment by fantoine** [comment]
It looks good to me to refactor it for Symfony 3. It's always better to keep updated.
Feel free to submit more PR.

**Pull request merged**
