### PR TITLE
Fix TokenProvider

### PR DESCRIPTION
**Pull request by enumag**
I found a bug in my refactored version. This should fix the problem.

### CODE REVIEW

**Comment by enumag** [comment]
Actually don't merge this yet. I have another thing to solve.

**Comment by enumag** [comment]
@fantoine All done now.

After you merge this, could you test the new version in one of your applications?

Also would you mind giving me write access to this repository? Just in case I find something else to fix and you're not immediately available.

**Comment by enumag** [comment]
ping @fantoine

**Comment by enumag** [comment]
ping @fantoine

**Comment by fantoine** [comment]
Sorry for the delay and thanks for your participation.
I also gave you write access to this repo if you need to push more fixes.

**Comment by enumag** [comment]
@fantoine Thank you!

**Pull request merged**
